In [2]:
# Dependencies
import pandas as pd
import json
import csv
import matplotlib.pyplot as plt
import numpy as np

In [8]:
file_name = "../minimizeddata/newmasterdata.csv"
master_df = pd.read_csv(file_name)
master_df.head()

,level_0,index,1. open,2. high,3. low,4. close,5. volume,Month,Day,Year,Company,daily change
0,4527,2017-12-29,170.52,170.590,169.220,169.23,25643711,December,Friday,2017,AAPL,-0.010814
1,4526,2017-12-28,171.00,171.850,170.480,171.08,15997739,December,Thursday,2017,AAPL,0.002814
2,4525,2017-12-27,170.10,170.780,169.710,170.60,21672062,December,Wednesday,2017,AAPL,0.000176
3,4524,2017-12-26,170.80,171.470,169.679,170.57,32968167,December,Tuesday,2017,AAPL,-0.025370
4,4523,2017-12-22,174.68,175.424,174.500,175.01,16052615,December,Friday,2017,AAPL,0.000000

In [18]:
names = master_df["Company"].unique()
names

array(['AAPL', 'AMZN', 'FB', 'GOOGL', 'MSFT'], dtype=object)

In [28]:
above_df = master_df.loc[(master_df["Year"] >= 2014), :]

for stock in names:
    stock_df = master_df.loc[(master_df["Company"] == stock), :]

In [30]:
stock_df

,level_0,index,1. open,2. high,3. low,4. close,5. volume,Month,Day,Year,Company,daily change
4028,4527,2017-12-29,85.630,86.0500,85.5000,85.540,18162779,December,Friday,2017,MSFT,-0.002100
4029,4526,2017-12-28,85.900,85.9300,85.5500,85.720,9872795,December,Thursday,2017,MSFT,0.000117
4030,4525,2017-12-27,85.650,85.9800,85.2150,85.710,13000828,December,Wednesday,2017,MSFT,0.003630
4031,4524,2017-12-26,85.310,85.5346,85.0300,85.400,9737412,December,Tuesday,2017,MSFT,-0.001286
4032,4523,2017-12-22,85.400,85.6300,84.9200,85.510,14033977,December,Friday,2017,MSFT,0.000117
4033,4522,2017-12-21,86.050,86.1000,85.4000,85.500,16638402,December,Thursday,2017,MSFT,-0.000234
4034,4521,2017-12-20,86.200,86.3000,84.7100,85.520,23425009,December,Wednesday,2017,MSFT,-0.003612
4035,4520,2017-12-19,86.350,86.3500,85.2700,85.830,23241979,December,Tuesday,2017,MSFT,-0.006367
4036,4519,2017-12-18,87.120,87.4999,86.2300,86.380,21551076,December,Monday,2017,MSFT,-0.005412
4037,4518,2017-12-15,85.260,87.0900,84.8800,86.850,52430167,December,Friday,2017,MSFT,0.025505
4038,4517,2017-12-14,85.430,85.8739,84.5300,84.690,19080106,December,Thursday,2017,MSFT,-0.007733
4039,4516,2017-12-13,85.740,86.0000,85.1700,85.350,21307911,December,Wednesday,2017,MSFT,-0.002688
4040,4515,2017-12-12,85.310,86.0500,85.0800,85.580,23534946,December,Tuesday,2017,MSFT,0.004107
4041,4514,2017-12-11,84.290,85.3700,84.1200,85.230,19909119,December,Monday,2017,MSFT,0.012714
4042,4513,2017-12-08,83.630,84.5800,83.3300,84.160,23825056,December,Friday,2017,MSFT,0.020245
4043,4512,2017-12-07,82.540,82.8000,82.0000,82.490,20378114,December,Thursday,2017,MSFT,-0.003503
4044,4511,2017-12-06,81.550,83.1400,81.4300,82.780,24821403,December,Wednesday,2017,MSFT,0.014585
4045,4510,2017-12-05,81.340,82.6800,80.9801,81.590,25512120,December,Tuesday,2017,MSFT,0.006290
4046,4509,2017-12-04,84.420,84.4299,80.7000,81.080,37977732,December,Monday,2017,MSFT,-0.037740
4047,4508,2017-12-01,83.600,84.8100,83.2200,84.260,29387325,December,Friday,2017,MSFT,0.001069
4048,4507,2017-11-30,83.510,84.5200,83.3400,84.170,32998408,November,Thursday,2017,MSFT,0.009959
4049,4506,2017-11-29,84.710,84.9172,83.1750,83.340,27358477,November,Wednesday,2017,MSFT,-0.018143
4050,4505,2017-11-28,84.070,85.0600,84.0200,84.880,21162639,November,Tuesday,2017,MSFT,0.012042
4051,4504,2017-11-27,83.310,83.9800,83.3000,83.870,17603760,November,Monday,2017,MSFT,0.007326
4052,4503,2017-11-24,83.010,83.4300,82.7800,83.260,7425503,November,Friday,2017,MSFT,0.001805
4053,4502,2017-11-22,83.830,83.9000,83.0400,83.110,20213704,November,Wednesday,2017,MSFT,-0.007286
4054,4501,2017-11-21,82.740,83.8400,82.7400,83.720,21237454,November,Tuesday,2017,MSFT,0.014419
4055,4500,2017-11-20,82.400,82.5900,82.2500,82.530,16072495,November,Monday,2017,MSFT,0.001578
4056,4499,2017-11-17,83.120,83.1200,82.2400,82.400,21715498,November,Friday,2017,MSFT,-0.009615
4057,4498,2017-11-16,83.100,83.4200,82.9400,83.200,20659209,November,Thursday,2017,MSFT,0.002651
...,...,...,...,...,...,...,...,...,...,...,...,...
5005,3550,2014-02-13,37.330,37.8600,37.3300,37.610,37635500,February,Thursday,2014,MSFT,0.003736
5006,3549,2014-02-12,37.350,37.6000,37.3000,37.470,27051800,February,Wednesday,2014,MSFT,0.007935
5007,3548,2014-02-11,36.880,37.2600,36.8600,37.175,32141400,February,Tuesday,2014,MSFT,0.010190
5008,3547,2014-02-10,36.630,36.8000,36.2900,36.800,26767000,February,Monday,2014,MSFT,0.006565
5009,3546,2014-02-07,36.320,36.5900,36.0100,36.560,33260500,February,Friday,2014,MSFT,0.010503
5010,3545,2014-02-06,35.800,36.2500,35.6900,36.180,35351800,February,Thursday,2014,MSFT,0.010050
5011,3544,2014-02-05,36.290,36.4700,35.8000,35.820,55814400,February,Wednesday,2014,MSFT,-0.014580
5012,3543,2014-02-04,36.970,37.1890,36.2500,36.350,54697900,February,Tuesday,2014,MSFT,-0.003564
5013,3542,2014-02-03,37.740,37.9850,36.4300,36.480,64063100,February,Monday,2014,MSFT,-0.035941
5014,3541,2014-01-31,36.950,37.8900,36.5600,37.840,93162300,January,Friday,2014,MSFT,0.026587
5015,3540,2014-01-30,36.790,36.8800,36.2300,36.860,35036300,January,Thursday,2014,MSFT,0.005456
5016,3539,2014-01-29,35.980,36.8800,35.9000,36.660,52745900,January,Wednesday,2014,MSFT,0.010753
5017,3538,2014-01-28,36.120,36.3900,35.7500,36.270,36205500,January,Tuesday,2014,MSFT,0.006661
5018,3537,2014-01-27,36.870,36.8900,35.9800,36.030,44420800,January,Monday,2014,MSFT,-0.021057
5019,3536,2014-01-24,37.450,37.5500,36.5300,36.805,76395500,January,Friday,2014,MSFT,0.020802
5020,3535,2014-01-23,36.090,36.1300,35.5200,36.055,43954000,January,Thursday,2014,MSFT,0.003479
5021,3534,2014-01-22,36.260,36.3200,35.7500,35.930,21904300,January,Wednesday,2014,MSFT,-0.006635
5022,3533,2014-01-21,36.820,36.8200,36.0600,36.170,31567300,January,Tuesday,2014,MSFT,-0.005772
5023,3532,2014-01-17,36.830,36.8300,36.1500,36.380,46267500,January,Friday,2014,MSFT,-0.013825
5024,3531,2014-01-16,36.690,37.0000,36.3100,36.890,38018700,January,Thursday,2014,MSFT,0.003536
5025,3530,2014-01-15,35.900,36.7900,35.8500,36.760,44812600,January,Wednesday,2014,MSFT,0.027390
5026,3529,2014-01-14,34.730,35.8800,34.6300,35.780,41623300,January,Tuesday,2014,MSFT,0.022870
5027,3528,2014-01-13,35.990,36.0200,34.8300,34.980,45901900,January,Monday,2014,MSFT,-0.029412
5028,3527,2014-01-10,35.900,36.1500,35.7500,36.040,40548800,January,Friday,2014,MSFT,0.014354
5029,3526,2014-01-09,35.880,35.9100,35.4000,35.530,36516300,January,Thursday,2014,MSFT,-0.006432
5030,3525,2014-01-08,36.000,36.1400,35.5800,35.760,59971700,January,Wednesday,2014,MSFT,-0.017852
5031,3524,2014-01-07,36.325,36.4900,36.2100,36.410,35802800,January,Tuesday,2014,MSFT,0.007750
5032,3523,2014-01-06,36.850,36.8900,36.1100,36.130,43603700,January,Monday,2014,MSFT,-0.021132
5033,3522,2014-01-03,37.200,37.2200,36.6000,36.910,31134800,January,Friday,2014,MSFT,-0.006728
5034,3521,2014-01-02,37.350,37.4000,37.1000,37.160,30632200,January,Thursday,2014,MSFT,-0.006683